/**
 * Verifies trainer.ts against core/msomi_trainer.py directly, not just
 * "looks reasonable" — see trainer.ts's own header for the porting
 * rationale (plain-JS gradient descent, no new dependency).
 *
 * `pythonReferenceFixture.json` was generated by actually running the
 * real Python trainer (`core/msomi_trainer.train()`) against the
 * fixed decision set below, via:
 *
 *   python3 -c "
 *   from core import msomi_trainer as mt
 *   model = mt.train(decisions, ['cards_played', 'empties_hand'],
 *                     human_weight=2.0, iterations=500, learning_rate=0.3)
 *   "
 *
 * (see the fixture file's own `decisions` field for the exact input,
 * copied verbatim from that run). Both the input and the Python
 * output are captured in the fixture so this test can assert the TS
 * port produces the SAME weights on the SAME input — genuine
 * cross-language parity, not a hand-derived expectation.
 */
import { describe, expect, it } from 'vitest';
import {
  MsomiTrainingError,
  TRAINABLE_FEATURES,
  loadDecisionsFromText,
  scoreOption,
  trainConditionalLogit,
  validateModel,
} from '../trainer.js';
import type { MsomiDecisionRecord, MsomiTrainedModel } from '@kadi/adapter-interface';
import fixture from './pythonReferenceFixture.json' with { type: 'json' };

const referenceDecisions = fixture.decisions as unknown as MsomiDecisionRecord[];
const referenceModel = fixture.model as unknown as MsomiTrainedModel;

describe('trainConditionalLogit — parity with the real Python trainer', () => {
  it('matches core/msomi_trainer.py train() weights on the same input', () => {
    const model = trainConditionalLogit(referenceDecisions, ['cards_played', 'empties_hand'], {
      humanWeight: referenceModel.training.human_weight,
      iterations: referenceModel.training.iterations,
      learningRate: referenceModel.training.learning_rate,
    });

    expect(model.weights.cards_played).toBeCloseTo(referenceModel.weights.cards_played, 6);
    expect(model.weights.empties_hand).toBeCloseTo(referenceModel.weights.empties_hand, 6);
    expect(model.training.num_decisions).toBe(referenceModel.training.num_decisions);
    expect(model.training.num_human_decisions).toBe(referenceModel.training.num_human_decisions);
    expect(model.training.num_ai_decisions).toBe(referenceModel.training.num_ai_decisions);
    expect(model.training.train_agreement).toBeCloseTo(referenceModel.training.train_agreement, 6);
    expect(model.training.train_agreement_human_only).toBeCloseTo(
      referenceModel.training.train_agreement_human_only as number,
      6,
    );
    expect(model.schema_version).toBe(referenceModel.schema_version);
    expect(model.decision_schema_version).toBe(referenceModel.decision_schema_version);
    expect(model.model_type).toBe('conditional_logit');
  });
});

function decision(
  isHuman: boolean,
  chosenRank: number,
  opts: Record<string, unknown>[],
): MsomiDecisionRecord {
  return {
    schema_version: 1,
    game_id: 'g1',
    is_human: isHuman,
    player_name: 'p',
    difficulty: 'MEDIUM',
    hand_before: [],
    hand_count: 5,
    top_card: null,
    pickup_pending: 0,
    declared_kadi: false,
    chosen_rank: chosenRank,
    num_options: opts.length,
    options: opts.map((o) => ({ cards: null, is_draw: false, score: 0, ...o })),
  };
}

describe('trainConditionalLogit — behavior', () => {
  it('throws when no features are selected', () => {
    expect(() => trainConditionalLogit(referenceDecisions, [])).toThrow(MsomiTrainingError);
  });

  it('throws for a feature outside TRAINABLE_FEATURES', () => {
    expect(() => trainConditionalLogit(referenceDecisions, ['not_a_real_feature'])).toThrow(MsomiTrainingError);
  });

  it('throws when no decision has more than one real option', () => {
    const onlyOneOption = [decision(true, 0, [{ cards_played: 1 }])];
    expect(() => trainConditionalLogit(onlyOneOption, ['cards_played'])).toThrow(
      /nothing to learn from/,
    );
  });

  it('skips single-option decisions but still trains on the rest', () => {
    const decisions = [
      decision(true, 0, [{ cards_played: 1 }]), // skipped — only one option
      decision(true, 0, [{ cards_played: 2 }, { cards_played: 0 }]),
      decision(false, 1, [{ cards_played: 0 }, { cards_played: 2 }]),
    ];
    const model = trainConditionalLogit(decisions, ['cards_played'], { iterations: 200 });
    expect(model.training.num_decisions).toBe(2);
  });

  it('a higher cards_played weight predicts the option with more cards played, given enough consistent training data', () => {
    const decisions = Array.from({ length: 20 }, (_, i) =>
      decision(i % 2 === 0, 0, [{ cards_played: 3 }, { cards_played: 1 }]),
    );
    const model = trainConditionalLogit(decisions, ['cards_played'], { iterations: 300 });
    expect(model.weights.cards_played).toBeGreaterThan(0);
    expect(model.training.train_agreement).toBe(1);
  });

  it('is deterministic given the same inputs', () => {
    const a = trainConditionalLogit(referenceDecisions, ['cards_played', 'empties_hand'], { iterations: 100 });
    const b = trainConditionalLogit(referenceDecisions, ['cards_played', 'empties_hand'], { iterations: 100 });
    expect(a.weights).toEqual(b.weights);
  });
});

describe('scoreOption', () => {
  it('is a plain weighted sum over the model weights', () => {
    const model: MsomiTrainedModel = {
      schema_version: 1,
      decision_schema_version: 1,
      model_type: 'conditional_logit',
      features: ['cards_played', 'empties_hand'],
      weights: { cards_played: 2, empties_hand: 5 },
      training: {
        num_decisions: 1,
        num_human_decisions: 1,
        num_ai_decisions: 0,
        human_weight: 2,
        iterations: 1,
        learning_rate: 0.1,
        train_agreement: 1,
        train_agreement_human_only: 1,
      },
    };
    expect(scoreOption(model, { cards_played: 3, empties_hand: true })).toBe(2 * 3 + 5 * 1);
  });

  it('treats a missing feature as 0, matching training-time encoding', () => {
    const model: MsomiTrainedModel = {
      schema_version: 1,
      decision_schema_version: 1,
      model_type: 'conditional_logit',
      features: ['cards_played'],
      weights: { cards_played: 10 },
      training: {
        num_decisions: 1,
        num_human_decisions: 0,
        num_ai_decisions: 1,
        human_weight: 2,
        iterations: 1,
        learning_rate: 0.1,
        train_agreement: 1,
        train_agreement_human_only: null,
      },
    };
    expect(scoreOption(model, {})).toBe(0);
  });
});

describe('validateModel', () => {
  const baseModel: MsomiTrainedModel = {
    schema_version: 1,
    decision_schema_version: 1,
    model_type: 'conditional_logit',
    features: ['cards_played'],
    weights: { cards_played: 1 },
    training: {
      num_decisions: 1,
      num_human_decisions: 1,
      num_ai_decisions: 0,
      human_weight: 2,
      iterations: 1,
      learning_rate: 0.1,
      train_agreement: 1,
      train_agreement_human_only: 1,
    },
  };

  it('accepts a well-formed current-version model', () => {
    expect(validateModel(baseModel)).toBeNull();
  });

  it('rejects a non-object', () => {
    expect(validateModel(null)).toMatch(/Not a valid model file/);
    expect(validateModel('a string')).toMatch(/Not a valid model file/);
  });

  it('rejects a mismatched model schema version', () => {
    expect(validateModel({ ...baseModel, schema_version: 999 })).toMatch(/different MSOMI format/);
  });

  it('rejects a mismatched decision schema version', () => {
    expect(validateModel({ ...baseModel, decision_schema_version: 999 })).toMatch(
      /different game version/,
    );
  });

  it('rejects a model with no weights', () => {
    expect(validateModel({ ...baseModel, weights: {} })).toMatch(/no learned weights/);
  });

  it("rejects a model referencing a feature this version doesn't recognize", () => {
    expect(validateModel({ ...baseModel, weights: { not_a_real_feature: 1 } })).toMatch(
      /doesn't recognize/,
    );
  });
});

describe('TRAINABLE_FEATURES', () => {
  it('matches core/msomi_trainer.py TRAINABLE_FEATURES exactly (13 features)', () => {
    expect(TRAINABLE_FEATURES).toEqual([
      'cards_played',
      'cards_remaining',
      'empties_hand',
      'wastes_win',
      'leaves_kadi',
      'unanswered_question',
      'pickup_value_added',
      'has_suit_change',
      'has_skip',
      'has_kickback',
      'has_question',
      'next_is_threat',
      'stranded_cluster_cost',
    ]);
  });
});

describe('loadDecisionsFromText', () => {
  const rec1 = decision(true, 0, [{ cards_played: 1 }, { cards_played: 2 }]);
  const rec2 = decision(false, 1, [{ cards_played: 3 }, { cards_played: 0 }]);

  it('parses multiple files, skips blank lines, and tallies human/ai counts', () => {
    const file1 = `${JSON.stringify(rec1)}\n\n${JSON.stringify(rec2)}\n`;
    const { decisions, stats } = loadDecisionsFromText([file1]);
    expect(decisions).toHaveLength(2);
    expect(stats).toEqual({
      loaded: 2,
      skippedSchemaMismatch: 0,
      skippedUnparseable: 0,
      humanCount: 1,
      aiCount: 1,
    });
  });

  it('skips unparseable lines without aborting the whole load', () => {
    const file1 = `not json\n${JSON.stringify(rec1)}\n`;
    const { decisions, stats } = loadDecisionsFromText([file1]);
    expect(decisions).toHaveLength(1);
    expect(stats.skippedUnparseable).toBe(1);
  });

  it('skips records with a mismatched or missing schema_version', () => {
    const stale = { ...rec1, schema_version: 999 };
    const file1 = `${JSON.stringify(stale)}\n${JSON.stringify(rec2)}\n`;
    const { decisions, stats } = loadDecisionsFromText([file1]);
    expect(decisions).toHaveLength(1);
    expect(stats.skippedSchemaMismatch).toBe(1);
  });

  it('respects includeHuman/includeAi filters', () => {
    const file1 = `${JSON.stringify(rec1)}\n${JSON.stringify(rec2)}\n`;
    const humanOnly = loadDecisionsFromText([file1], { includeAi: false });
    expect(humanOnly.decisions).toHaveLength(1);
    expect(humanOnly.decisions[0].is_human).toBe(true);

    const aiOnly = loadDecisionsFromText([file1], { includeHuman: false });
    expect(aiOnly.decisions).toHaveLength(1);
    expect(aiOnly.decisions[0].is_human).toBe(false);
  });

  it('concatenates decisions from multiple files, no limit on how many', () => {
    const file1 = `${JSON.stringify(rec1)}\n`;
    const file2 = `${JSON.stringify(rec2)}\n`;
    const { decisions } = loadDecisionsFromText([file1, file2]);
    expect(decisions).toHaveLength(2);
  });
});
